# Generated by Django 4.0.6 on 2022-08-23 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='домен')),
            ],
            options={
                'verbose_name': 'Доменное имя',
                'verbose_name_plural': 'Доменные имена',
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=200, verbose_name='длинная ссылка')),
                ('short_url', models.CharField(max_length=200, unique=True, verbose_name='сокращенная ссылка')),
                ('clicks', models.IntegerField(blank=True, default=0, null=True, verbose_name='количество кликов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshorter.domain', verbose_name='домен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткая ссылки',
            },
        ),
    ]
