# Generated by Django 4.0.6 on 2022-08-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='lifetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
